parameters:
    core.agence_manager.class: CoreBundle\Services\Manager\Admin\AgenceManager
    core.entity.agence_manager.class: CoreBundle\Entity\Admin\Agence
    core.entityname.agence_manager.class: 'CoreBundle\Entity\Admin\Agence'
    core.argname.agence_manager.class: 'L''agence'

    core.service_manager.class: CoreBundle\Services\Manager\Admin\ServiceManager
    core.entity.service_manager.class: CoreBundle\Entity\Admin\Service
    core.entityname.service_manager.class: 'CoreBundle\Entity\Admin\Service'
    core.argname.service_manager.class: 'Le service'

    core.manager_service_link_manager.class: CoreBundle\Services\Manager\Admin\ManagerServiceLinkManager
    core.entity.manager_service_link_manager.class: CoreBundle\Entity\Admin\ManagerServiceLink
    core.entityname.manager_service_link_manager.class: 'CoreBundle\Entity\Admin\ManagerServiceLink'
    core.argname.manager_service_link_manager.class: 'Ce Manager de Service'

    core.entite_holding_manager.class: CoreBundle\Services\Manager\Admin\EntiteHoldingManager
    core.entity.entite_holding.class: CoreBundle\Entity\Admin\EntiteHolding
    core.entityname.entite_holding.class: 'CoreBundle\Entity\Admin\EntiteHolding'
    core.argname.entite_holding.class: 'L''entit√©'

    core.utilisateur_manager.class: CoreBundle\Services\Manager\Admin\UtilisateurManager
    core.entity.utilisateur_manager.class: CoreBundle\Entity\Admin\Utilisateur
    core.entityname.utilisateur_manager.class: 'CoreBundle\Entity\Admin\Utilisateur'
    core.argname.utilisateur_manager.class: 'L''utilisateur'

    core.utilisateur_photo_manager.class: CoreBundle\Services\Manager\Admin\UtilisateurPhotoManager
    core.entity.utilisateur_photo_manager.class: CoreBundle\Entity\Admin\UtilisateurPhoto
    core.entityname.utilisateur_photo_manager.class: 'CoreBundle\Entity\Admin\UtilisateurPhoto'
    core.argname.utilisateur_photo_manager.class: 'La Photo de l''Utilisateur'

    core.fonction_manager.class: CoreBundle\Services\Manager\Admin\FonctionManager
    core.entity.fonction_manager.class: CoreBundle\Entity\Admin\Fonction
    core.entityname.fonction_manager.class: 'CoreBundle\Entity\Admin\Fonction'
    core.argname.fonction_manager.class: 'La fonction'

    core.candidat_manager.class: CoreBundle\Services\Manager\Admin\CandidatManager
    core.entity.candidat_manager.class: CoreBundle\Entity\Admin\Candidat
    core.entityname.candidat_manager.class: 'CoreBundle\Entity\Admin\Candidat'
    core.argname.candidat_manager.class: 'Le candidat'

    core.utilisateur_log_action_manager.class: CoreBundle\Services\Manager\UtilisateurLogActionManager
    core.entity.utilisateur_log_action_manager.class: CoreBundle\Entity\UtilisateurLogAction
    core.entityname.utilisateur_log_action_manager.class: 'CoreBundle\Entity\UtilisateurLogAction'
    core.argname.utilisateur_log_action_manager.class: 'Cet historique'

services:
    core.agence_manager:
        class: '%core.agence_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.agence_manager.class%"]]
        - [setEntityName, ["%core.entityname.agence_manager.class%"]]
        - [setArgname, ["%core.argname.agence_manager.class%"]]

    core.utilisateur_manager:
        class: '%core.utilisateur_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.utilisateur_manager.class%"]]
        - [setEntityName, ["%core.entityname.utilisateur_manager.class%"]]
        - [setArgname, ["%core.argname.utilisateur_manager.class%"]]

    core.utilisateur_photo_manager:
        class: '%core.utilisateur_photo_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.utilisateur_photo_manager.class%"]]
        - [setEntityName, ["%core.entityname.utilisateur_photo_manager.class%"]]
        - [setArgname, ["%core.argname.utilisateur_photo_manager.class%"]]

    core.fonction_manager:
        class: '%core.fonction_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.fonction_manager.class%"]]
        - [setEntityName, ["%core.entityname.fonction_manager.class%"]]
        - [setArgname, ["%core.argname.fonction_manager.class%"]]

    core.service_manager:
        class: '%core.service_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.service_manager.class%"]]
        - [setEntityName, ["%core.entityname.service_manager.class%"]]
        - [setArgname, ["%core.argname.service_manager.class%"]]

    core.manager_service_link_manager:
        class: '%core.manager_service_link_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.manager_service_link_manager.class%"]]
        - [setEntityName, ["%core.entityname.manager_service_link_manager.class%"]]
        - [setArgname, ["%core.argname.manager_service_link_manager.class%"]]

    core.entite_holding_manager:
        class: '%core.entite_holding_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.entite_holding.class%"]]
        - [setEntityName, ["%core.entityname.entite_holding.class%"]]
        - [setArgname, ["%core.argname.entite_holding.class%"]]

    core.candidat_manager:
        class: '%core.candidat_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.candidat_manager.class%"]]
        - [setEntityName, ["%core.entityname.candidat_manager.class%"]]
        - [setArgname, ["%core.argname.candidat_manager.class%"]]

    core.utilisateur_log_action_manager:
        class: '%core.utilisateur_log_action_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%core.entity.utilisateur_log_action_manager.class%"]]
        - [setEntityName, ["%core.entityname.utilisateur_log_action_manager.class%"]]
        - [setArgname, ["%core.argname.utilisateur_log_action_manager.class%"]]