parameters:
    core.curl_wrap.class: CoreBundle\Services\CurlWrap
    core.zendesk_service.class: CoreBundle\Services\ZendeskService
    core.google_api_service.class: CoreBundle\Services\GoogleApiService
    core.odigo_api_service.class: CoreBundle\Services\OdigoApiService
    core.active_directory_api_service.class: CoreBundle\Services\ActiveDirectoryApiService
    core.salesforce_api_service.class: CoreBundle\Services\SalesforceApiService

    security.acces_service.class: CoreBundle\Services\Security\AccesService

services:
    core.curl_wrap:
        class: %core.curl_wrap.class%

    core.zendesk_service:
        class: %core.zendesk_service.class%
        arguments: [ '@core.curl_wrap', '@core.app_zendesk_ticket_link_manager', '@core.parameters_calls' ]

    core.google_api_service:
        class: %core.google_api_service.class%
        arguments: [ '@core.utilisateur_manager' ]

    core.odigo_api_service:
        class: %core.odigo_api_service.class%
        arguments: [ '@core.utilisateur_manager', '@core.odigotelliste_manager', '@core.orangetelliste_manager', '@core.prosodie_odigo_manager', '@core.service_manager', '@core.fonction_manager', '@odigo.service.client' ]

    core.salesforce_api_service:
        class: %core.salesforce_api_service.class%
        arguments: [ '@core.salesforcetoken_store', '@security.token_storage', '@core.factory.apps.salesforce.salesforce_user', '@core.prosodie_odigo_manager', '@core.agence_manager', '@core.service_manager', '@core.fonction_manager', '@core.parameters_calls', '@core.aramisagency_manager' ]

    core.active_directory_api_service:
        class: %core.active_directory_api_service.class%
        arguments: [ '@core.service_manager', '@core.utilisateur_manager' ]

    security.acces_service:
        class: %security.acces_service.class%
        calls:
        - [ setContainer , [ "@service_container" ]]