imports:
    - { resource: parameters.yml }
    - { resource: security_prod.yml }
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

light_saml_symfony_bridge:
    own:
        entity_id: https://aramiam.aramisauto.com
        credentials:
                    -
                        certificate: "%kernel.root_dir%/config/saml.crt"
                        key:         "%kernel.root_dir%/config/saml.pem"
                        password:     ""
    party:
        idp:
            files:
                - "%kernel.root_dir%/config/federationmetadata_clphoto.xml"

    store:
        id_state: app.id_store  # name of id store service created in step 6

light_saml_sp:
    username_mapper:
        # default fallback list of attributes for
        # lightsaml_sp.username_mapper.simple service to use to
        # resolve SAML Response to username
        - "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"
        - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        - "http://schemas.xmlsoap.org/claims/EmailAddress"
        - "http://schemas.xmlsoap.org/claims/CommonName"
        - "urn:oid:0.9.2342.19200300.100.1.3"
        - "uid"
        - "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
        - "@name_id@"