imports:
    - { resource: security_dev.yml }
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
light_saml_symfony_bridge:
    own:
        entity_id: https://nasxa02.clphoto.fr:8080
        credentials:
                    -
                        certificate: "%kernel.root_dir%/config/saml.crt"
                        key:         "%kernel.root_dir%/config/saml.pem"
                        password:     ""
    party:
        idp:
            files:
                - "%kernel.root_dir%/config/federationmetadata_clphoto.xml"

    store:
        id_state: app.id_store  # name of id store service created in step 6

light_saml_sp:
    username_mapper:
        # default fallback list of attributes for
        # lightsaml_sp.username_mapper.simple service to use to
        # resolve SAML Response to username
        - "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"
        - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        - "http://schemas.xmlsoap.org/claims/EmailAddress"
        - "http://schemas.xmlsoap.org/claims/CommonName"
        - "urn:oid:0.9.2342.19200300.100.1.3"
        - "uid"
        - "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
        - "@name_id@"