dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

salesforce_api_bundle:
    resource: "@SalesforceApiBundle/Resources/config/routing.yml"
    prefix:   /

odigo_api_bundle:
    resource: "@OdigoApiBundle/Resources/config/routing.yml"
    prefix:   /

active_directory_api_bundle:
    resource: "@ActiveDirectoryApiBundle/Resources/config/routing.yml"
    prefix:   /

google_api_bundle:
    resource: "@GoogleApiBundle/Resources/config/routing.yml"
    prefix:   /

aramis_api_bundle:
    resource: "@AramisApiBundle/Resources/config/routing.yml"
    prefix:   /

core_bundle:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

mailer_bundle:
    resource: "@MailerBundle/Resources/config/routing.yml"
    prefix:   /