salesforce_api:
    resource: "@SalesforceApiBundle/Resources/config/routing.yml"
    prefix:   /

odigo_api:
    resource: "@OdigoApiBundle/Resources/config/routing.yml"
    prefix:   /

active_directory_api:
    resource: "@ActiveDirectoryApiBundle/Resources/config/routing.yml"
    prefix:   /

aramis_api:
    resource: "@AramisApiBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

