# app/config/security.yml
security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        main:
            light_saml_sp:
                provider: db_provider       # user provider name configured in step 9
                user_creator: user_creator  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
            logout:
                path: /logout
            anonymous: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/agences/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/fonctions/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/services/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/candidats/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }