parameters:
    salesforce.profile_manager.class: SalesforceApiBundle\Services\Manager\SalesforceProfileManager
    salesforce.entity.profile_manager.class: SalesforceApiBundle\Entity\SalesforceProfile
    salesforce.entityname.profile_manager.class: 'SalesforceApiBundle\Entity\SalesforceProfile'
    salesforce.argname.profile_manager.class: 'Le Profil Salesforce'

    salesforce.groupe_manager.class: SalesforceApiBundle\Services\Manager\SalesforceGroupeManager
    salesforce.entity.groupe_manager.class: SalesforceApiBundle\Entity\SalesforceGroupe
    salesforce.entityname.groupe_manager.class: 'SalesforceApiBundle\Entity\SalesforceGroupe'
    salesforce.argname.groupe_manager.class: 'Le groupe Salesforce'

    salesforce.token_store.class: SalesforceApiBundle\Services\Manager\SalesforceTokenStoreManager
    salesforce.entity.token_store.class: SalesforceApiBundle\Entity\SalesforceTokenStore
    salesforce.entityname.token_store.class: 'SalesforceApiBundle\Entity\SalesforceTokenStore'
    salesforce.argname.token_store.class: 'Le token de connexion Salesforce'

    salesforce.service_cloud_acces.class: SalesforceApiBundle\Services\Manager\SalesforceServiceCloudAccesManager
    salesforce.entity.service_cloud_acces.class: SalesforceApiBundle\Entity\SalesforceServiceCloudAcces
    salesforce.entityname.service_cloud_acces.class: 'SalesforceApiBundle\Entity\SalesforceServiceCloudAcces'
    salesforce.argname.service_cloud_acces.class: 'L''acc√®s Service Cloud'

    salesforce.groupe_to_fonction_manager.class: SalesforceApiBundle\Services\Manager\SalesforceGroupeMatchFonctionManager
    salesforce.entity.groupe_to_fonction_manager.class: SalesforceApiBundle\Entity\SalesforceGroupeMatchFonction
    salesforce.entityname.groupe_to_fonction_manager.class: 'SalesforceApiBundle\Entity\SalesforceGroupeMatchFonction'
    salesforce.argname.groupe_to_fonction_manager.class: 'Le groupe Salesforce'

    salesforce.salesforce_api_service.class: SalesforceApiBundle\Services\SalesforceApiService

    salesforce.factory.salesforce_user.class: SalesforceApiBundle\Factory\SalesforceUserFactory

services:
    salesforce.salesforceprofile_manager:
        class: %salesforce.profile_manager.class%
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%salesforce.entity.profile_manager.class%"]]
        - [setEntityName, ["%salesforce.entityname.profile_manager.class%"]]
        - [setArgname, ["%salesforce.argname.profile_manager.class%"]]

    salesforce.salesforcegroupe_manager:
        class: %salesforce.groupe_manager.class%
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%salesforce.entity.groupe_manager.class%"]]
        - [setEntityName, ["%salesforce.entityname.groupe_manager.class%"]]
        - [setArgname, ["%salesforce.argname.groupe_manager.class%"]]

    salesforce.salesforcetoken_store:
        class: %salesforce.token_store.class%
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%salesforce.entity.token_store.class%"]]
        - [setEntityName, ["%salesforce.entityname.token_store.class%"]]
        - [setArgname, ["%salesforce.argname.token_store.class%"]]

    salesforce.service_cloud_acces_manager:
        class: %salesforce.service_cloud_acces.class%
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%salesforce.entity.service_cloud_acces.class%"]]
        - [setEntityName, ["%salesforce.entityname.service_cloud_acces.class%"]]
        - [setArgname, ["%salesforce.argname.service_cloud_acces.class%"]]

    salesforce.groupe_to_fonction_manager:
        class: %salesforce.groupe_to_fonction_manager.class%
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%salesforce.entity.groupe_to_fonction_manager.class%"]]
        - [setEntityName, ["%salesforce.entityname.groupe_to_fonction_manager.class%"]]
        - [setArgname, ["%salesforce.argname.groupe_to_fonction_manager.class%"]]

    salesforce.salesforce_api_service:
        class: %salesforce.salesforce_api_service.class%
        arguments: [ '@salesforce.salesforcetoken_store', '@security.token_storage', '@salesforce.factory.salesforce_user', '@odigo.prosodie_odigo_manager', '@core.agence_manager', '@core.service_manager', '@core.fonction_manager', '@app.parameters_calls', '@aramis.aramisagency_manager', '@salesforce.service_cloud_acces_manager' ]

    salesforce.factory.salesforce_user:
        class: %salesforce.factory.salesforce_user.class%
        parent: core.factory.abstract